INSERT INTO USUARIO (ID, EMAIL, NOME, SENHA) VALUES( NULL, 'rita@gmail.com', 'Rita de Cássia dos Santos', '$2y$10$hLAr7RYw7lhoT/TXbuAJi.cccIPx1RBcJsgvNYJirl1nC1ZuBBypS');
INSERT INTO USUARIO (ID, EMAIL, NOME, SENHA) VALUES( NULL, 'amanda@gmail.com', 'Amanda Larissa', '$2a$10$cgDDANa2pOPAr3LS/s6xQOWOxf.mYVnp.f9EN7ojMU8zJOznhDYL.');

INSERT INTO TAREFA (ID, CONCLUIDA, DESCRICAO, PRIORIDADE, USUARIO_ID) VALUES(NULL, FALSE, 'Estudo', 0, 1);
INSERT INTO TAREFA (ID, CONCLUIDA, DESCRICAO, PRIORIDADE, USUARIO_ID) VALUES(NULL, FALSE, 'Jogar videogame', 2, 1);
INSERT INTO TAREFA (ID, CONCLUIDA, DESCRICAO, PRIORIDADE, USUARIO_ID) VALUES(NULL, TRUE, 'Lavar louças', 1, 1);
INSERT INTO TAREFA (ID, CONCLUIDA, DESCRICAO, PRIORIDADE, USUARIO_ID) VALUES(NULL, FALSE, 'ler um livro', 1, 1);
INSERT INTO TAREFA (ID, CONCLUIDA, DESCRICAO, PRIORIDADE, USUARIO_ID) VALUES(NULL, FALSE, 'ler um livro', 1, 2);

